api = "0.4"

[buildpack]
id = "portersupport/heroku-buildpack-wkhtmltopdf-1"
version = "0.1"
name = "wkhtmltopdf"
homepage = "https://github.com/portersupport/heroku-buildpack-wkhtmltopdf-1"

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"
